fix(order): prevent multiple handouts of a blid
boklisten/bl-api pull request #443
Opened 2023-04-17 12:17 UTC by LarsSelbekk

There was already a check to prevent a blid from being added to an order if it already belongs to another order, but if the order had been fulfilled (i.e. the blid handed out), the item could be handed out to another person without first being handed in. This commit fixes that by checking whether some blid in an order is not handed in. In that case, it returns an error with code 801 (409 in the HTTP response).

There are some customeritems which do not have blids, which means we cannot prevent those items from being handed out again. However, some research indicates that these are legacy items of which there are exceedingly few which are not handed in (~55 at time of writing).

2023-04-17 12:18 UTC, LarsSelbekk commented
![](https://github.trello.services/images/mini-trello-icon.png) [En bl-ID kan deles ut flere ganger til forskjellige kunder](https://trello.com/c/qvXf6C5t/491-en-bl-id-kan-deles-ut-flere-ganger-til-forskjellige-kunder)

2023-04-18 09:18 UTC, AdrianAndersen requested changes

2023-04-18 09:18 UTC, AdrianAndersen commented on src/collections/order/operations/place/order-place.operation.ts
> +      .filter((blid) => blid != null);
```suggestion
    const handoutItems = order.orderItems.filter(
      (orderItem) =>
        handoutOrderTypes.has(orderItem.type) && orderItem.blid !== null
    );
```

2023-04-18 09:18 UTC, AdrianAndersen commented on src/collections/order/operations/place/order-place.operation.ts
> +      .filter((blid) => blid != null);
Very minor, but I think it would be more readable and clean if you refactored this to something like "handoutItems", to denote exactly what it is. (instead of just a list of blids from the order). Then, you could just map out the blids in the aggregate function.

2023-04-18 11:14 UTC, LarsSelbekk commented on src/collections/order/operations/place/order-place.operation.ts
> +      .filter((blid) => blid != null);
Changed, but I kept the null-check as `!=` because I don't trust that it won't be `undefined` - it's MongoDB we're dealing with here :p

2023-04-18 11:22 UTC, AdrianAndersen commented on src/collections/order/operations/place/order-place.operation.ts
> +      .filter((blid) => blid != null);
Yeah, better safe than sorry

2023-04-18 11:23 UTC, AdrianAndersen approved these changes

2023-04-18 11:24 UTC, AdrianAndersen commented
Looks good now! Remember to test in staging before pushing to the prod, @LarsSelbekk  🚀

2023-04-18 11:24 UTC, merged