Create new match endpoints
boklisten/bl-api pull request #447
Opened 2023-05-11 14:31 UTC by LarsSelbekk

- refactor(BlCollection): extract BlCollection-names to enum
- chore(blStorageHandler): use strict mongoose schema typing
- WIP: Update Match & allow variants in BlDocument

2023-06-10 06:48 UTC, AdrianAndersen requested changes
Overall, it is looking good! I have some questions and some small fixups, but I think this is very close to being gucci. Seems like it is working as intended. 🚀

In terms of adding location, that will be really easy to plug in in my PR.

2023-06-10 06:48 UTC, AdrianAndersen commented on src/collections/match/hooks/match-hook-utils.ts
> +  }));
Duplicate code from getSenders

2023-06-10 06:48 UTC, AdrianAndersen commented on src/collections/match/hooks/match.post.generate.hook.ts
> +      ).code(907); // TODO: wrong code
Forgotten TODO? If you think this should be done later, it should be put in a Trello card

2023-06-10 06:48 UTC, AdrianAndersen commented on src/collections/match/match.collection.ts
> +          restriction: {permissions: ["admin"]},
Why is this not also super? For now I think only we should be able to trigger this. (Even though we might make a UI for admins later)

2023-06-10 06:48 UTC, AdrianAndersen commented on src/collections/match/match.schema.ts
> +    date: { type: Date, required: true },
`required: true` does not sound nullable

2023-06-10 06:48 UTC, AdrianAndersen commented on src/collections/match/match.schema.ts
> +  sender: { type: ObjectId, ref: BlCollectionName.UserDetails, default: undefined },
Why do you need a default value for all of these? They should be required, not nullable imo

2023-06-10 06:48 UTC, AdrianAndersen commented on src/server/server.ts
> -
💩

2023-06-10 06:48 UTC, AdrianAndersen commented on src/storage/blDocumentStorage.ts
> +    return this.mongoDbHandler.addMany(docs);
How was this not implemented before lol

2023-06-10 18:27 UTC, LarsSelbekk commented on src/collections/match/hooks/match.post.generate.hook.ts
> +      ).code(907); // TODO: wrong code
Oops forgot that one, will have to make a new error code

2023-06-10 18:27 UTC, LarsSelbekk commented on src/collections/match/match.collection.ts
> +          restriction: {permissions: ["admin"]},
Didn't realize we were super, thought we were admin. Will change

2023-06-10 18:39 UTC, LarsSelbekk commented on src/collections/match/match.schema.ts
> +  sender: { type: ObjectId, ref: BlCollectionName.UserDetails, default: undefined },
Because of the way I implemented variants. :(
There's really only one schema (see the type at the bottom), so the schema contains the union of all variant fields (plus base fields). If the variant fields were required, a StandMatch would have to provide values for the UserMatch fields. To make them required would necessitate having several schemas and models for Match, which I did try to do, but it has cascading effects throughout the codebase - we would have to choose the correct variant model when interacting with the collection. I could write code for that, probably, but it would take much longer. This way, only Typescript ensures that the fields are correct, but it does work.

The fields are default undefined instead of null because then only the actually relevant fields (i.e. belonging to the correct variant) exist, making it much more understandable.

2023-06-10 18:40 UTC, LarsSelbekk commented on src/server/server.ts
> -
Do you miss those lines? :p

2023-06-10 18:40 UTC, LarsSelbekk commented on src/storage/blDocumentStorage.ts
> +    return this.mongoDbHandler.addMany(docs);
dunno :)

2023-06-10 18:48 UTC, LarsSelbekk commented on src/collections/match/match.schema.ts
> +    date: { type: Date, required: true },
You are of course correct, I thought I had read that `null` would be allowed (but not `undefined` or unset), but I can't find that and the documentation implies otherwise. Fixing.

2023-06-10 18:58 UTC, LarsSelbekk commented on src/collections/match/match.collection.ts
> +          restriction: {permissions: ["admin"]},
Actually, we are only admin, if I change it to super we can't. I guess the permissions aren't transitive though, so I'll add super as well.
![image](https://github.com/boklisten/bl-api/assets/6224384/9a5ad0cd-9914-4c39-a8b1-167fd61f9c45)

2023-06-10 19:33 UTC, LarsSelbekk commented on src/collections/match/hooks/match-hook-utils.ts
> +  }));
Thought it would be too unreadable/generic if I refactored it, and nearly every line is different, but I managed to do it in one way at least.

2023-06-10 19:50 UTC, LarsSelbekk commented on src/collections/match/match.schema.ts
> +    date: { type: Date, required: true },
Fixed in 161eb16

2023-06-10 19:50 UTC, LarsSelbekk commented on src/collections/match/hooks/match.post.generate.hook.ts
> +      ).code(907); // TODO: wrong code
Fixed in 161eb16

2023-06-10 19:50 UTC, LarsSelbekk commented on src/collections/match/hooks/match-hook-utils.ts
> +  }));
Fixed in 161eb16

2023-06-10 19:50 UTC, LarsSelbekk commented on src/collections/match/match.collection.ts
> +          restriction: {permissions: ["admin"]},
Added in 161eb16

2023-06-10 19:52 UTC, LarsSelbekk commented on src/collections/match/match.schema.ts
> +  sender: { type: ObjectId, ref: BlCollectionName.UserDetails, default: undefined },
https://mongoosejs.com/docs/5.x/docs/discriminators.html

2023-06-11 07:30 UTC, AdrianAndersen commented on src/server/server.ts
> -
nah, I just find it funny that I forgot to remove them hehe

2023-06-11 12:24 UTC, AdrianAndersen commented on src/collections/match/hooks/match-hook-utils.ts
> +  }));
nice solution 💯

2023-06-11 12:34 UTC, AdrianAndersen commented on src/collections/match/match.collection.ts
> +          restriction: {permissions: ["admin"]},
Ah, yeah. the structure is actually customer < employee < manager < admin < super. In that case, I am not sure what super is haha. But that works for now yh.

2023-06-11 12:37 UTC, AdrianAndersen commented on src/collections/match/match.schema.ts
> +  sender: { type: ObjectId, ref: BlCollectionName.UserDetails, default: undefined },
sure, it is a bit out of scope to fix this now anyways. There are probably more important improvements of our schemas we should do first 😛

2023-06-11 12:38 UTC, AdrianAndersen approved these changes
LGTM

2023-06-11 12:38 UTC, merged