Match Meeting Info Assignment
boklisten/bl-api pull request #454
Opened 2023-06-11 16:39 UTC by AdrianAndersen

- refactor: extract match testing methods
- feat: assign time and location for matches
- feat: attach time and location assignment to match-generate-operation

With this PR, we now generate an actual time and location for each match, after the match genereation. This is integrated into the match-genereate-operation.

2023-06-11 16:40 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Generere optimalt møtetidspunkt og sted for matches](https://trello.com/c/fNWZNG1o/632-generere-optimalt-m%C3%B8tetidspunkt-og-sted-for-matches)

2023-06-11 18:38 UTC, LarsSelbekk requested changes
Preddy good. These comments are mostly me being picky, I know the second to last one will bite me at some point if it's not fixed.

2023-06-11 18:38 UTC, LarsSelbekk commented on src/collections/match/helpers/match-finder-2/match-meeting-info.spec.ts
> +      expect(simultaneousMatches <= simultaneousMatchLimit).to.be.true;
```suggestion
      expect(simultaneousMatches).to.be.lessThanOrEqual(simultaneousMatchLimit);
```
Better failure message

2023-06-11 18:38 UTC, LarsSelbekk commented on src/collections/match/helpers/match-finder-2/match-meeting-info.spec.ts
> +      );
```suggestion
      const simultaneousMatches = meetingTimes.filter(
        (next) => next.getTime() === distinctMeetingTime.getTime()
      ).length;
      );
```

2023-06-11 18:38 UTC, LarsSelbekk commented on src/collections/match/operations/match-operation-utils.ts
> +    !isNaN(new Date(m.startTime).getTime())
Should also parse this to a Date instead of lying to Typescript; it will then lie to us and say startTime is a Date, even though it's still a string. Not sure the best way to do that; maybe change the verify function to return the parsed object and throw an exception if it's invalid (or since the type is quite a bit more complicated now, throw an exception with a specific error message to the condition that is violated).

2023-06-11 18:46 UTC, LarsSelbekk commented on src/collections/match/operations/match-operation-utils.ts
> +        typeof location.name === "string" && location.name.length > 0
Should verify simultaneousMatchLimit also, if it's present
```suggestion
        typeof location.name === "string" &&
        location.name.length > 0 &&
        (location.simultaneousMatchLimit === undefined ||
          (Number.isInteger(location.simultaneousMatchLimit) &&
            location.simultaneousMatchLimit > 0))
```

2023-06-11 18:49 UTC, AdrianAndersen commented on src/collections/match/helpers/match-finder-2/match-meeting-info.ts
> +  locationMeetingTimes: { [locationName: string]: Date[] },
agree 👍🏻

2023-06-11 18:58 UTC, AdrianAndersen commented on src/collections/match/helpers/match-finder-2/match-meeting-info.ts
> +    !userMatches.every((userMatch) => {
Hmm, I can't really imagine a scenario where it would generate more matches. Since we check that for every match, there has been generated a `UserMatchWithMeetingInfo` it should at least have all the matches it needs to.

But yeah, I added a simple length check to verify that there are no dupes or weird behaviour.

2023-06-11 19:09 UTC, AdrianAndersen commented on src/collections/match/operations/match-operation-utils.ts
> +    !isNaN(new Date(m.startTime).getTime())
I changed the type in MatcherSpec to `string`, which is what it actually is. I think it is a bit overboard to make this method return something, and that it should suffice that we call it a string. (and know that it will be a valid dateStr because of this test)

Agree?

2023-06-11 19:09 UTC, AdrianAndersen commented on src/collections/match/operations/match-operation-utils.ts
> +        typeof location.name === "string" && location.name.length > 0
Yup, I concur

2023-06-11 19:10 UTC, AdrianAndersen commented
Addressed your comments in https://github.com/boklisten/bl-api/pull/454/commits/e7a0c6a99dbf240459d4a1a3e3b2e8548088eaac 😘

2023-06-11 19:11 UTC, LarsSelbekk commented on src/collections/match/operations/match-operation-utils.ts
> +    !isNaN(new Date(m.startTime).getTime())
Sure, I guess

2023-06-11 19:14 UTC, LarsSelbekk commented on src/collections/match/helpers/match-finder-2/match-meeting-info.spec.ts
> +    );
Oops forgot one
```suggestion
    const distinctMeetingTimes = new Set(meetingTimes);
```

2023-06-11 19:15 UTC, LarsSelbekk commented on src/collections/match/helpers/match-finder-2/match-meeting-info.spec.ts
> +    );
Not sure that works, will test

2023-06-11 19:17 UTC, AdrianAndersen commented on src/collections/match/helpers/match-finder-2/match-meeting-info.spec.ts
> +    );
Huh, actually surprised we can use a Set() here. I assumed the check for uniqueness in Set() would be the object reference, not if the actual Date was the same. 🤠

2023-06-11 19:17 UTC, AdrianAndersen commented on src/collections/match/helpers/match-finder-2/match-meeting-info.spec.ts
> +    );
But yeah, nice find!

2023-06-11 19:18 UTC, LarsSelbekk commented on src/collections/match/helpers/match-finder-2/match-meeting-info.spec.ts
> +    );
Hmm I guess not. Could do something like this, but that's not a lot better.
`Array.from(new Set(meetingTimes.map(d => d.getTime()))).map(t => new Date(t))`

2023-06-11 19:19 UTC, LarsSelbekk commented on src/collections/match/helpers/match-finder-2/match-meeting-info.spec.ts
> +    );
Did you try it out? In my testing the dates counted as different even if the times were the same

2023-06-11 19:19 UTC, AdrianAndersen commented on src/collections/match/helpers/match-finder-2/match-meeting-info.spec.ts
> +    );
But it actually works with only using the new Set() constructor. Dunno why 🤷‍♂️

2023-06-11 19:19 UTC, AdrianAndersen commented on src/collections/match/helpers/match-finder-2/match-meeting-info.spec.ts
> +    );
The the solution you suggested is gucci

2023-06-11 19:21 UTC, LarsSelbekk commented on src/collections/match/helpers/match-finder-2/match-meeting-info.spec.ts
> +    );
Huh GitHub interleaved our comments there a bit, I didn't see yours before now. It didn't work for me, but it did for you?

2023-06-11 19:24 UTC, LarsSelbekk commented on src/collections/match/helpers/match-finder-2/match-meeting-info.spec.ts
> +    );
Ok I tested in the debugger, it seems the duplicates were actually the same instances, but we can't rely on that happening so I don't think this change is correct after all

2023-06-11 19:25 UTC, AdrianAndersen commented on src/collections/match/helpers/match-finder-2/match-meeting-info.spec.ts
> +    );
Yup 
```typescript
console.log(meetingTimes)
> [
  2023-02-02T11:00:00.000Z,
  2023-02-02T11:00:00.000Z,
  2023-02-02T11:15:00.000Z,
  2023-02-02T11:15:00.000Z,
  2023-02-02T11:30:00.000Z
]
console.log(new Set(meetingTimes))
> Set(3) {
  2023-02-02T11:00:00.000Z,
  2023-02-02T11:15:00.000Z,
  2023-02-02T11:30:00.000Z
}
```

2023-06-11 19:25 UTC, LarsSelbekk commented on src/collections/match/helpers/match-finder-2/match-meeting-info.spec.ts
> +    );
You can choose whether to revert it, use my other suggestion or find your own solution

2023-06-11 19:31 UTC, LarsSelbekk approved these changes

2023-06-11 19:33 UTC, merged

2023-06-12 19:45 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Forlenging av bøker ved bestilling](https://trello.com/c/duxliqpH/659-forlenging-av-b%C3%B8ker-ved-bestilling)