feat(match): add 'me'-endpoint for matches
boklisten/bl-api pull request #455
Opened 2023-06-14 00:24 UTC by LarsSelbekk

2023-06-14 00:28 UTC, LarsSelbekk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Skjule andre sine matches i APIet](https://trello.com/c/mOvznm3b/662-skjule-andre-sine-matches-i-apiet)

2023-06-14 00:30 UTC, LarsSelbekk commented
I'm aware there's a TODO in there to move some types to bl-model, but I really can't be bothered to bump bl-model right now. If you want to, that's great.

2023-06-14 13:02 UTC, AdrianAndersen requested changes

2023-06-14 14:16 UTC, AdrianAndersen commented on src/collections/match/operations/match-getall-me.operation.ts
> +        value: blApiRequest.user.id,
Why not use the primary key for userDetail?

```suggestion
        fieldName: "_id",
        value: blApiRequest.user.id,
```

2023-06-14 20:16 UTC, LarsSelbekk commented on src/collections/match/operations/match-getall-me.operation.ts
> +        value: blApiRequest.user.id,
@AdrianAndersen

2023-06-14 20:22 UTC, LarsSelbekk commented on src/collections/match/operations/match-getall-me.operation.ts
> +    });
Done

2023-06-14 20:22 UTC, LarsSelbekk commented on src/collections/match/operations/match-getall-me.operation.ts
> +  }
Done

2023-06-15 07:59 UTC, AdrianAndersen commented on src/collections/match/operations/match-getall-me.operation.ts
> +        value: blApiRequest.user.id,
It certainly does include the userDetail primary key. 

However, it seems like the API `handleRequest` (higher order method) did not forward it to `blApiRequest` for some reason. That is stupid, so I changed it.😛

2023-06-15 08:02 UTC, AdrianAndersen approved these changes

2023-06-15 08:05 UTC, merged

2023-06-15 10:28 UTC, LarsSelbekk commented on src/collections/match/operations/match-getall-me.operation.ts
> +        value: blApiRequest.user.id,
Ah ok, I only looked at the actual properties in the debugger