match order generation
boklisten/bl-api pull request #459
Opened 2023-06-16 13:07 UTC by AdrianAndersen

- refactor: extract getAllMatchesForUser
- feat: match-order-generation (temp commit)

2023-06-16 21:47 UTC, LarsSelbekk requested changes

2023-06-16 21:47 UTC, LarsSelbekk commented on src/collections/match/operations/match-operation-utils.ts
> +  const newRentPeriod = branch?.paymentInfo?.rentPeriods?.[0];
Why is there not an undefined-check on the branch?

2023-06-16 21:47 UTC, LarsSelbekk commented on src/collections/match/operations/match-operation-utils.ts
> +    throw new BlError("Branch rent period is same is customer item deadline");
```suggestion
    throw new BlError("Branch rent period is same as customer item deadline");
```

2023-06-16 21:47 UTC, LarsSelbekk commented on src/collections/match/operations/match-operation-utils.ts
> +        item: item.id,
Is there no reference to the customerItem or uniqueItem which is being moved?

2023-06-16 21:47 UTC, LarsSelbekk commented on src/collections/match/operations/match-transfer-item.operation.ts
> +      new BlDocumentStorage(BlCollectionName.UserDetails, userDetailSchema);
Use fancy `??=`-syntax :p

2023-06-16 21:47 UTC, LarsSelbekk commented on src/collections/match/operations/match-transfer-item.operation.ts
> +  }
This is a very useful helper method which should probably be located somewhere else - maybe even bl-model, since it's kind of a type-thing, though I understand if you don't agree.

2023-06-16 21:47 UTC, LarsSelbekk commented on src/collections/match/operations/match-transfer-item.operation.ts
> +    if (!blid || typeof blid !== "string" || blid.length === 0) {
Feel like length = 0 is the same as `not a valid blid`, so no extra check necessary

2023-06-16 21:47 UTC, LarsSelbekk commented on src/collections/match/operations/match-transfer-item.operation.ts
> +      throw new BlError("blid not active").code(804);
Shouldn't errors be in Norwegian since they can be shown to the user?

2023-06-16 21:47 UTC, LarsSelbekk commented on src/collections/match/operations/match-transfer-item.operation.ts
> +      userFeedback = `Boken du har scannet tilhørte opprinnelig en annen kunde. Boken er nå registrert på deg, men avsender må fortsatt levere sin opprinnelig bok. Ta kontakt med stand for spørsmål.`
```suggestion
      userFeedback = `Boken du har scannet tilhørte noen andre enn den du skulle motta fra. Det kan bety at hen har byttet bok med noen andre. Boken er nå registrert på deg, men hen er fortsatt ansvarlig for at den opprinnelige boken blir levert. Ta kontakt med stand for spørsmål.`;
```
I think this should really be in bl-next, but that's a bit harder to do currently and we don't have much time, so I'll allow it.

2023-06-16 21:47 UTC, LarsSelbekk commented on src/collections/match/operations/match-transfer-item.operation.ts
> +    const dryRun = false;
Assuming this is a testing option? It probably wouldn't hurt to make it an optional request parameter

2023-06-16 21:48 UTC, LarsSelbekk commented
Haven't tested this since it's a draft and I have my own PR to work on, trust you'll do fine.

2023-06-16 22:04 UTC, LarsSelbekk commented on src/collections/match/operations/match-transfer-item.operation.ts
> +      (userMatch) =>
I know this is probably impossible for our first semester of matching, but I would feel better checking that `userMatch.sender === customerItem.customer` (or w.e. is correct) to verify that it's not a match where they're receiving the item. Since as far as I remember we don't filter on active matches yet, this will otherwise give false positives if the original owner received it via P2P previously.

2023-06-16 22:15 UTC, LarsSelbekk commented on src/collections/match/operations/match-transfer-item.operation.ts
> +        await matchStorage.update(
I just noticed I added an `orders`-property to `Match`; if you want to, we can delete it, or otherwise you can add it to the mongoose schema and append to it here

2023-06-17 22:45 UTC, LarsSelbekk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Generere ordre ved overlevering](https://trello.com/c/1wdwvIoB/610-generere-ordre-ved-overlevering)

2023-06-18 09:47 UTC, AdrianAndersen commented on src/collections/match/operations/match-operation-utils.ts
> +        item: item.id,
nope, it only points to the order it is moved to / moved from. That is the magic of our db 🦑

2023-06-18 09:51 UTC, AdrianAndersen commented on src/collections/match/operations/match-transfer-item.operation.ts
> +  }
I feel like it is weird to have it in bl-model. Maybe if we had like a shared logic package. (Which we absolutely should have had, since there is so much shared logic). For now, I moved it into match operation utils, so it is easy to access / move later.

2023-06-18 09:52 UTC, AdrianAndersen commented on src/collections/match/operations/match-transfer-item.operation.ts
> +    if (!blid || typeof blid !== "string" || blid.length === 0) {
yeah, isValidBlid covers this statement actually

2023-06-18 09:55 UTC, LarsSelbekk commented on src/collections/match/operations/match-transfer-item.operation.ts
> +      userFeedback = `Boken du har scannet tilhørte opprinnelig en annen kunde. Boken er nå registrert på deg, men avsender må fortsatt levere sin opprinnelig bok. Ta kontakt med stand for spørsmål.`
Oops did forget an E in "opprinnelige", hope you spotted it

2023-06-18 09:55 UTC, AdrianAndersen commented on src/collections/match/operations/match-transfer-item.operation.ts
> +        await matchStorage.update(
#maybeinthefuture 🚅

2023-06-18 10:00 UTC, AdrianAndersen commented on src/collections/match/operations/match-transfer-item.operation.ts
> +      (userMatch) =>
Hm, not sure I understand what you mean here. We do filter out that senders matches earlier, we only need to find the exact match where this item belongs. (So checking sender === customer should be redundant since we have filtered on senderMatches already)

2023-06-18 10:09 UTC, LarsSelbekk commented on src/collections/match/operations/match-transfer-item.operation.ts
> +      (userMatch) =>
I can't look at the rest of the code right now, but my impression was that it was a list of matches the sender was involved in, but not necessarily as the sender. Now that I'm thinking it through that likely isn't the case since that's harder than finding only the ones where they're the sender, so you're probably correct

2023-06-18 10:40 UTC, AdrianAndersen commented
So imma just merge now

2023-06-18 10:41 UTC, merged