fix: support UTF-8 for auto capitalization
boklisten/bl-api pull request #468
Opened 2023-08-24 08:45 UTC by AdrianAndersen

2023-08-24 08:46 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [UTF-8 support for auto-kapitalisering](https://trello.com/c/kMmgUkuG/788-utf-8-support-for-auto-kapitalisering)

2023-08-25 08:51 UTC, LarsSelbekk requested changes

2023-08-25 11:50 UTC, LarsSelbekk commented
Seems to work great. Probably shouldn't accept `2` as birthdate, but that's not relevant.

![image](https://github.com/boklisten/bl-api/assets/6224384/6f4205a9-43cf-4799-a867-1f9ff44c73cf)

![image](https://github.com/boklisten/bl-api/assets/6224384/5e3eb6d6-77ec-4c39-b8b2-6be728d8fa2d)

2023-08-25 12:01 UTC, LarsSelbekk commented on src/collections/user-detail/hooks/user-detail-update.hook.ts
> +      .map((w) => w[0].toUpperCase() + w.slice(1))
This might have some edge cases where lowercasing and then uppercasing a letter will be different from doing nothing. I don't know of any examples, but in German for example, uppercase "ß" is "SS", there might be something like it in the other direction. It probably won't be a problem, but I would like to not have another bug report about this in a month. Therefore I think we should only do `toLowerCase` on the sliced part (the non-first-letter characters).

2023-08-29 09:18 UTC, AdrianAndersen commented on src/collections/user-detail/hooks/user-detail-update.hook.ts
> +      .map((w) => w[0].toUpperCase() + w.slice(1))
fixed

2023-08-29 09:18 UTC, AdrianAndersen commented on src/collections/user-detail/hooks/user-detail-update.hook.ts
> +      .map((w) => w[0].toUpperCase() + w.slice(1))
dunzo

2023-08-29 09:26 UTC, LarsSelbekk approved these changes

2023-08-29 09:26 UTC, merged