fix(error-handler): update blid already handed out message
boklisten/bl-api pull request #469
Opened 2023-08-29 16:21 UTC by LarsSelbekk

2023-08-29 16:21 UTC, LarsSelbekk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Oppdatere feilmelding når blid allerede er delt ut til noen andre](https://trello.com/c/o3P9m2SL/796-oppdatere-feilmelding-n%C3%A5r-blid-allerede-er-delt-ut-til-noen-andre)

2023-08-30 05:55 UTC, AdrianAndersen requested changes

2023-08-30 05:55 UTC, AdrianAndersen commented on src/bl-error/bl-error-handler.ts
> +          "En eller flere av bøkene du prøver å dele ut er allerede aktiv på en annen kunde. Prøv å dele ut én og én bok for å finne synderen.";
I know you quoted Bjørgen directly, but we _cannot_ use the word "synderen" 💩  
```suggestion
          "En eller flere av bøkene du prøver å dele ut er allerede aktiv på en annen kunde. Prøv å dele ut én og én bok for å finne ut hvilke bøker dette gjelder.";
```

2023-09-06 12:25 UTC, AdrianAndersen approved these changes
Prime 🍺

2023-09-06 12:25 UTC, merged