Upgrade password reset flow
boklisten/bl-api pull request #479
Opened 2023-11-02 15:38 UTC by LarsSelbekk

- fix(error-handler): don't reuse accessToken invalid code
- fix: remove duplicated bad format error code
- feat: allow creating db-doc with given ID
- feat: upgrade password reset flow

2023-11-02 15:46 UTC, LarsSelbekk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sikkerhetshull: kan endre hvem som helst sitt passord](https://trello.com/c/xkpYdkXG/812-sikkerhetshull-kan-endre-hvem-som-helst-sitt-passord)

2023-11-08 08:39 UTC, AdrianAndersen requested changes
Please make sure the create password reset always returns 200 to avoid username lookups

2023-11-08 08:39 UTC, AdrianAndersen commented on src/collections/pending-password-reset/hooks/pending-password-reset-post.hook.ts
> +    }
remove pls

2023-11-08 08:39 UTC, AdrianAndersen commented on src/collections/pending-password-reset/hooks/pending-password-reset-post.hook.ts
> +    }
dis too

2023-11-08 08:39 UTC, AdrianAndersen commented on src/collections/pending-password-reset/hooks/pending-password-reset-post.hook.ts
> +      });
needs an error code

2023-11-08 08:39 UTC, AdrianAndersen commented on src/collections/pending-password-reset/hooks/pending-password-reset-post.hook.ts
> +      .passwordReset(user.id, passwordResetRequest.email, `${id}:${token}`)
Please concat the id and token inside this method

2023-11-08 08:39 UTC, AdrianAndersen commented on src/collections/pending-password-reset/operations/confirm-pending-password-reset.operation.ts
> +    const [pendingPasswordResetId, candidateToken] =
Can you use query params here?

2023-11-08 08:40 UTC, AdrianAndersen commented
I still get everything back from the http://localhost:1337/pendingpasswordresets endpoint when I create a password reset 🧑‍🏫

2023-11-15 16:03 UTC, LarsSelbekk commented on src/collections/pending-password-reset/hooks/pending-password-reset-post.hook.ts
> +    }
Done

2023-11-15 16:03 UTC, LarsSelbekk commented on src/collections/pending-password-reset/hooks/pending-password-reset-post.hook.ts
> +    }
Done

2023-11-15 16:03 UTC, LarsSelbekk commented on src/collections/pending-password-reset/hooks/pending-password-reset-post.hook.ts
> +      });
Done

2023-11-15 16:04 UTC, LarsSelbekk commented on src/collections/pending-password-reset/hooks/pending-password-reset-post.hook.ts
> +      .passwordReset(user.id, passwordResetRequest.email, `${id}:${token}`)
N/A when using query params

2023-11-15 16:04 UTC, LarsSelbekk commented on src/collections/pending-password-reset/operations/confirm-pending-password-reset.operation.ts
> +    const [pendingPasswordResetId, candidateToken] =
Done

2023-11-15 16:04 UTC, LarsSelbekk commented
> I still get everything back from the http://localhost:1337/pendingpasswordresets endpoint when I create a password reset 🧑‍🏫

Fixed

2023-11-22 11:15 UTC, AdrianAndersen approved these changes

2023-11-22 11:23 UTC, merged