Bump Mongoose And MongoDB Driver To Latest
boklisten/bl-api pull request #483
Opened 2024-01-19 16:03 UTC by AdrianAndersen

This PR bumps Mongoose and MongoDB such that we can finally bump our running MongoDB version. 

I had to make some schema changes, but it should in theory be non breaking 🤞🏻 
I have tested my changes locally with MongoDB 7.0, and tested the most common use cases. (renting in bl-web, viewing info, bl-admin handouts/handins)

This version of Mongoose has stricter runtime validation, which means it throws more errors when we have misalignments in our scheme. It is therefore vital that we test this throughly so we eliminate as many errors as possible before prod.

2024-01-19 16:12 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Oppgradere MongoDB-driver](https://trello.com/c/D8YimcLt/829-oppgradere-mongodb-driver)

2024-01-20 17:46 UTC, LarsSelbekk requested changes
Some questions and suggestions, looks mostly good. From my thorough reading of the mongoose upgrade guides ([5->6](https://mongoosejs.com/docs/migrating_to_6.html), [6->7](https://mongoosejs.com/docs/migrating_to_7.html), [7->8](https://mongoosejs.com/docs/migrating_to_8.html)) we should be safe to upgrade, though I couldn't find mention of the supposed increased strictness. Tested a little with ordering books, cancel, matching, seems to work as far as I can tell.

2024-01-20 22:45 UTC, AdrianAndersen commented
The strictness is just by my observation - it throws runtime exceptions when you use Schemas that are not aligned with Typescript

2024-01-24 09:40 UTC, AdrianAndersen commented on src/collections/booking/booking.schema.ts
> -  },
Here we have the same issue as discussed earlier with the arrays. The only reason this works other places is because those places have type for instance `string | Item`. In Booking, we only have `branch: string;`. Therefore, we cannot make this required without the workaround we discussed in the meeting

2024-01-24 09:43 UTC, AdrianAndersen commented on fixtures/userdetails.ts
>      _id: ObjectId("61cded5a8f6c5c0047a21b4a"),
✅

2024-01-24 09:47 UTC, AdrianAndersen commented on src/collections/branch/branch.schema.ts
> +    responsible: Boolean,
I guess we can keep it as it was originally, dunno why I changed it.

2024-01-24 09:48 UTC, AdrianAndersen commented on src/collections/branch/branch.schema.ts
> -        default: false,
This value is not required, and the default value for mongoose is falsey. So a required: false and default: false should be the same as just an optional field.

2024-01-24 09:49 UTC, AdrianAndersen commented on src/collections/branch/branch.schema.ts
> -        default: false,
Again, default false is kinda redundant, since the actual unset value is falsey.

2024-01-24 09:49 UTC, AdrianAndersen commented on src/collections/branch/branch.schema.ts
>    },
Ditto as above

2024-01-24 09:50 UTC, AdrianAndersen commented on src/collections/customer-item/customer-item.schema.ts
>    type: {
This is both due to the default values being falsey, and the fact the we have the stupid ObjectId/string problem.

2024-01-24 10:13 UTC, AdrianAndersen commented on src/storage/mongoDb/mongoDb.blStorageHandler.ts
> +    return await document.save();
Fixed now 🧑‍🔧

2024-01-24 10:14 UTC, AdrianAndersen commented on src/storage/mongoDb/mongoDb.blStorageHandler.ts
> +      .findById<T>(id)
I agree, added it where applicable now

2024-01-24 11:02 UTC, LarsSelbekk approved these changes

2024-01-24 12:31 UTC, merged