Add API-endpoints for user-facing editable text
boklisten/bl-api pull request #484
Opened 2024-01-20 22:31 UTC by LarsSelbekk

- refactor(bl-endpiont): delete redundant files
- feat(bl-endpoint): add PUT endpoint
- refactor(mongoose): use built-in timestamping
- feat(editable-text): add endpoints for editing user-facing text
- chore: run prettier

2024-01-20 22:33 UTC, LarsSelbekk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Legge til admin-bestemt banner på forsiden](https://trello.com/c/Nd6SQ13z/719-legge-til-admin-bestemt-banner-p%C3%A5-forsiden)

2024-01-24 10:23 UTC, AdrianAndersen commented on src/collections/editable-text/hooks/editable-text.put.hook.ts
> +    this.editableTextStorage = editableTextStorage
??=

2024-01-24 10:25 UTC, AdrianAndersen commented on src/storage/mongoDb/mongoDb.blStorageHandler.ts
> +    console.log(result);
💩

2024-01-24 10:26 UTC, AdrianAndersen requested changes
Looks good! Just a few nits 🌞

2024-01-24 13:19 UTC, LarsSelbekk commented
Updated the upsert method in mongoDb.blStorageHandler to be called put, and changed its error handling slightly because of the Mongo upgrade.

2024-01-25 13:01 UTC, AdrianAndersen approved these changes
Gucci rockenrolla 🎸

2024-01-25 13:02 UTC, merged