Enable TS Strict Mode
boklisten/bl-api pull request #486
Opened 2024-01-27 10:30 UTC by AdrianAndersen

- build(TS): enable strict TS checks
- chore: use codemod to @ts-ignore all new strict mode errors

This PR enables strict mode for TS, along with a few other nifty strict checks. I have opted to just codemod ignore everything new, so that we can get better type checking for future features. This way, we can also gradually improve our codebase by fixing these ignores

2024-01-27 10:33 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Skru på streng typesjekking for bl-api](https://trello.com/c/lgRU1Tb5/885-skru-p%C3%A5-streng-typesjekking-for-bl-api)

2024-02-01 00:13 UTC, LarsSelbekk requested changes
Some nits, one major

2024-02-01 00:13 UTC, LarsSelbekk commented on src/messenger/email/email-service.ts
> +      delivery.info instanceof DeliveryInfoBring &&
Have you tested this? I'm not convinced it will work. [`instanceof`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof) seems to use the object prototype, which is set when the class constructor is used, which Mongoose won't do from my understanding. Since we don't have any kind of validator/parser (I'm considering looking into Zod), you would have to write a type guard to determine the type.

2024-02-01 00:13 UTC, LarsSelbekk commented on src/query/object-id-filter/db-query-object-id-filter.ts
>        param.length > 0
First and last line are identical

2024-02-01 00:13 UTC, LarsSelbekk commented on src/server/server.ts
> -    );
Wasn't this nice to have?

2024-02-01 08:51 UTC, AdrianAndersen commented on src/server/server.ts
> -    );
They could be, but in reality we have never set these environment variables, neither locally or on Render.

2024-02-07 09:23 UTC, AdrianAndersen commented on src/messenger/email/email-service.ts
> +      delivery.info instanceof DeliveryInfoBring &&
Yeah, true. I reverted this now, this PR is meant to be totally non breaking, so I went a bit overboard hehe

2024-02-07 09:23 UTC, AdrianAndersen commented on src/query/object-id-filter/db-query-object-id-filter.ts
>        param.length > 0
Fixed now

2024-02-07 14:12 UTC, LarsSelbekk approved these changes

2024-02-07 14:41 UTC, merged