feat(MatchGenerate): split senders and receivers
boklisten/bl-api pull request #517
Opened 2024-06-14 13:58 UTC by AdrianAndersen

2024-06-14 13:59 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Splitte MatcherSpec branches opp i senders og receivers](https://trello.com/c/P6XUZPnk/1065-splitte-matcherspec-branches-opp-i-senders-og-receivers)

2024-06-14 21:00 UTC, LarsSelbekk requested changes
Nits

2024-06-14 21:00 UTC, LarsSelbekk commented on src/collections/match/operations/match-generate-operation-helper.ts
>      ) &&
Use ObjectId-check

2024-06-14 21:00 UTC, LarsSelbekk commented on src/collections/match/operations/match-generate-operation-helper.ts
> +  receivers: string[];
I prefer senderBranches and receiverBranches like we had before, as this makes me expect user IDs.

2024-06-15 16:35 UTC, LarsSelbekk approved these changes

2024-06-15 16:52 UTC, merged