feat(match collection): add locking endpoint
boklisten/bl-api pull request #519
Opened 2024-06-14 19:41 UTC by AdrianAndersen

2024-06-14 19:41 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Mulighet for å låse/åpne overleveringer for brukere](https://trello.com/c/b8jlQD4k/1058-mulighet-for-%C3%A5-l%C3%A5se-%C3%A5pne-overleveringer-for-brukere)

2024-06-14 20:48 UTC, LarsSelbekk requested changes

2024-06-14 20:48 UTC, LarsSelbekk commented on src/collections/match/operations/match-lock.operation.ts
> +  const m = matchLockSpec as Record<string, unknown>;
```suggestion
  const m = matchLockSpec as Record<string, unknown> | null | undefined;
```
and maybe extract a type for this as we should be using this type more generally

2024-06-14 20:48 UTC, LarsSelbekk commented on src/collections/match/operations/match-lock.operation.ts
> +    m &&
```suggestion
    !!m &&
```

2024-06-14 20:48 UTC, LarsSelbekk commented on src/collections/match/operations/match-lock.operation.ts
> +  }
Should use separate declaration of the field so TypeScript knows it's not null - see order-place.operation.ts

2024-06-16 15:37 UTC, LarsSelbekk approved these changes

2024-06-17 13:03 UTC, merged