refactor(match): address previous PR comments
boklisten/bl-api pull request #525
Opened 2024-06-17 19:48 UTC by AdrianAndersen

2024-06-17 19:49 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rette kommentarer fra PRer som ble merget](https://trello.com/c/JD0AaW2l/1071-rette-kommentarer-fra-prer-som-ble-merget)

2024-06-17 19:49 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rette kommentarer fra PRer som ble merget](https://trello.com/c/JD0AaW2l/1071-rette-kommentarer-fra-prer-som-ble-merget)

2024-06-18 14:20 UTC, LarsSelbekk requested changes

2024-06-18 14:20 UTC, LarsSelbekk commented on src/collections/match/match.schema.ts
> +    type: Map,
Actually, we can use flattenObjectIds too
```typescript
    schema.set("toJSON", {
      transform: MongooseModelCreator.transformObject,
      flattenMaps: true,
      flattenObjectIds: true,
    });
    schema.set("toObject", {
      transform: MongooseModelCreator.transformObject,
      flattenMaps: true,
      flattenObjectIds: true,
    });
```
which simplifies `transformObject`

```typescript
  public static transformObject(doc: unknown, ret?: unknown): void {
    // Mongoose isn't sure which parameter to use, so try both :/
    if (!ret && doc) ret = doc;
    if (!ret) return;
    if (Array.isArray(ret)) {
      ret.forEach((document) =>
        MongooseModelCreator.transformObject({}, document),
      );
    } else if (typeof ret === "object") {
      const document = ret as Record<string, unknown>;
      // Translate _id to id only if id does not already exist
      // (embedded documents such as BlDocument.user may have an id field which is different from the _id field)
      if ("_id" in document && !("id" in document))
        document["id"] = document["_id"];
      delete document["_id"];
      delete document["__v"];
    }
  }
```

2024-06-18 14:20 UTC, LarsSelbekk commented on src/collections/match/operations/match-generate-operation-helper.ts
>        (entry) =>
```suggestion
      ([branchId, itemIds]) =>
```

2024-06-18 14:20 UTC, LarsSelbekk commented on src/collections/match/operations/match-generate-operation-helper.ts
> +      (deadlineOverride) =>
```suggestion
      ([branchId, newDeadline]) =>
```

2024-06-18 14:42 UTC, LarsSelbekk commented on src/collections/match/match.schema.ts
> +    type: Map,
Actually, Mongoose doesn't *actually* seem to return `Map`s, to this is moot. The ObjectId-transformation would still be helpful, but out of scope here.

2024-06-18 15:05 UTC, LarsSelbekk approved these changes
I fix

2024-06-18 17:33 UTC, AdrianAndersen commented
i approve 💯

2024-06-18 17:33 UTC, merged