feat(reports): create endpoint for generating customer item report xlsx files
boklisten/bl-api pull request #528
Opened 2024-06-25 17:01 UTC by AdrianAndersen

This is the first new endpoint for the report functionality. It aggregates the customerItems nicely depending on a few options, and responds with the complete xlsx file. I want to replace the client side fetching and xlsx processing with just doing it server side. That way, we keep the frontend dumb and easier to migrate to bl-next

2024-06-25 17:02 UTC, AdrianAndersen commented
Will probably make sense to generalise the xlsx logic later when I add more endpoints for reports

2024-06-25 17:05 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Endepunkt for å generere customerItem-rapporter](https://trello.com/c/AS1IRnVS/1110-endepunkt-for-%C3%A5-generere-customeritem-rapporter)

2024-06-25 20:09 UTC, LarsSelbekk requested changes

2024-06-25 20:09 UTC, LarsSelbekk commented on src/collections/customer-item/customer-item-generate-report.operation.ts
> +          isbn: { $first: "$itemInfo.info.isbn" },
It would be nice to convert the ISBN to a string, as Excel wants to display it in scientific notation now. Of course, I think it should have been stored as a string in the database already, but that's probably harder.

2024-06-25 20:09 UTC, LarsSelbekk commented on src/collections/customer-item/customer-item-generate-report.operation.ts
> +    const worksheet = utils.json_to_sheet(reportData);
In the future, it would be nice to use xlsx's ability to adjust column widths to fit content (mentioned in documentation). I would also have liked to have filter/sort automatically visible on the header row, but I couldn't find documentation about that

2024-07-02 19:20 UTC, AdrianAndersen commented on src/collections/customer-item/customer-item-generate-report.operation.ts
> +          pivot: "1",
Pivot is a excel hack that Jørgen uses 🤷🏻

2024-07-02 19:37 UTC, AdrianAndersen commented on src/collections/customer-item/customer-item-generate-report.operation.ts
> +  ): Promise<BlapiResponse> {
✅

2024-07-02 19:37 UTC, AdrianAndersen commented on src/collections/customer-item/customer-item-generate-report.operation.ts
> +    return new BlapiResponse([]);
✅

2024-07-02 19:37 UTC, AdrianAndersen commented on src/collections/customer-item/customer-item-generate-report.operation.ts
> +          isbn: { $first: "$itemInfo.info.isbn" },
✅

2024-07-02 19:37 UTC, AdrianAndersen commented on src/collections/customer-item/customer-item-generate-report.operation.ts
> +    const worksheet = utils.json_to_sheet(reportData);
Later ™️

2024-07-02 20:44 UTC, AdrianAndersen commented on src/collections/customer-item/customer-item-generate-report.operation.ts
> +          handoutTime: "$handoutInfo.time",
Sure, added it!

2024-07-02 21:27 UTC, LarsSelbekk approved these changes

2024-07-02 21:55 UTC, merged