feat(postal-code): add postal code endpoint
boklisten/bl-api pull request #530
Opened 2024-07-03 10:51 UTC by AdrianAndersen

2024-07-03 10:52 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Migrer bl-login til bl-next](https://trello.com/c/7I2TCzEZ/1123-migrer-bl-login-til-bl-next)

2024-07-03 14:06 UTC, LarsSelbekk requested changes

2024-07-03 14:06 UTC, LarsSelbekk commented on src/collections/delivery/operations/postal-code.operation.ts
> +      return new BlapiResponse([{ postalCity: response.postal_codes[0].city }]);
Try to avoid using low-level BlapiResponse, better to just return the data directly to get type safety

2024-07-03 14:06 UTC, LarsSelbekk commented on src/collections/delivery/operations/postal-code.operation.ts
> +      );
Maybe we should use `http.handler` to get the usual logging (might need some adaptation)

2024-07-03 14:06 UTC, LarsSelbekk commented on src/collections/delivery/operations/postal-code.operation.ts
> +      throw new BlError("failed to lookup postal code").data(error).code(500);
```suggestion
      throw new BlError("failed to lookup postal code").data(error).code(200);
```

2024-07-04 18:48 UTC, AdrianAndersen commented on src/collections/delivery/delivery.collection.ts
> +        },
This is for the registration form, so yes, even people that are not customers have access.

2024-07-04 18:59 UTC, AdrianAndersen commented on src/collections/delivery/operations/postal-code.operation.ts
> +      return new BlapiResponse([{ postalCity: response.postal_codes[0].city }]);
Huh, the Operation interface requires that you return either a boolean or a BlapiResponse. What do you mean?

2024-07-04 19:09 UTC, AdrianAndersen commented on src/collections/delivery/operations/postal-code.operation.ts
> +      throw new BlError("failed to lookup postal code").data(error).code(500);
✅

2024-07-04 19:10 UTC, AdrianAndersen commented on src/collections/delivery/operations/postal-code.operation.ts
> +      );
I used getWithQuery, even though we do not have  query, since that is what we do the other places we fetch from Bring. I did not make changes to the method, since I plan to do a whole rewrite of the http handler later anyways. (request is depricated)

2024-07-04 20:34 UTC, LarsSelbekk commented on src/collections/delivery/operations/postal-code.operation.ts
> +      return new BlapiResponse([{ postalCity: response.postal_codes[0].city }]);
Yes, idiot, was thinking of hooks

2024-07-04 20:37 UTC, LarsSelbekk requested changes

2024-07-04 20:37 UTC, LarsSelbekk commented on src/collections/delivery/delivery.collection.ts
> +          name: "postal-code",
I would also like the path to contain the verb/action (lookup)

2024-07-04 20:37 UTC, LarsSelbekk commented on src/collections/delivery/operations/postal-code-lookup.operation.ts
> +        return new BlapiResponse([{ postalCity: "" }]);
Can we return null instead of empty string?

2024-07-05 05:39 UTC, AdrianAndersen commented on src/collections/delivery/delivery.collection.ts
> +          name: "postal-code",
✅

2024-07-05 05:40 UTC, AdrianAndersen commented on src/collections/delivery/operations/postal-code-lookup.operation.ts
> +        return new BlapiResponse([{ postalCity: "" }]);
Certainly!

2024-07-05 10:43 UTC, LarsSelbekk approved these changes

2024-07-05 10:47 UTC, merged