sendgrid templates
boklisten/bl-api pull request #533
Opened 2024-07-06 13:41 UTC by AdrianAndersen

- **refactor(dotenv): use esm import**
- **feat(email-service): setup email templates**

2024-07-06 20:59 UTC, LarsSelbekk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sette opp Sendgrid Email Templates](https://trello.com/c/WNEtkR8u/1130-sette-opp-sendgrid-email-templates)

2024-07-06 21:45 UTC, LarsSelbekk requested changes

2024-07-06 21:45 UTC, LarsSelbekk commented on src/messenger/email/email-service.ts
> +    sgMail.setApiKey(process.env["SENDGRID_API_KEY"] ?? "SG.");
Dude please throw if not set

2024-07-06 21:45 UTC, LarsSelbekk commented on src/messenger/email/email-service.ts
> +      await sgMail.send({
I like the principle greatly, however ... the picture you added doesn't work in the new Outlook app on Windows. 🫨 It works in Domeneshop webmail and Android-Outlook, does it work in your Apple apps? It seems to be formatted as a base64 string in the failing Outlook, but an external asset which must be downloaded in Domeneshop, which I assume means Microsoft is doing some proxy downloading on their server to obfuscate my IP and building it into the email.

2024-07-07 11:42 UTC, AdrianAndersen commented on src/messenger/email/email-service.ts
> +    sgMail.setApiKey(process.env["SENDGRID_API_KEY"] ?? "SG.");
I implemented assertEnv for all environment variables. The current approach was jalla 🤠 
https://github.com/boklisten/bl-api/pull/533/commits/fdeae7b9617d09408247ba873b9f70939cfe7004

2024-07-07 13:21 UTC, AdrianAndersen commented on src/messenger/email/email-service.ts
> +      await sgMail.send({
I updated the image to be an <img> with a href to a statically hosted version of our logo, and now it seems to work on all my mail clients at least, including Outlook:

<img width="852" alt="Screenshot 2024-07-07 at 15 20 02" src="https://github.com/boklisten/bl-api/assets/26925695/e7c605c7-8eaf-404d-b203-66b59e2e19ff">

2024-07-07 17:18 UTC, LarsSelbekk commented on src/messenger/email/email-service.ts
> +      await sgMail.send({
I've tested this wayyyy too much, and landed on the problem: the default links are `http`, not `https`. If we merely add that tiny little letter, the images work. Of course, that does impact the drag-and-drop concept.

The most annoying thing is that the `Email Test` feature in SendGrid doesn't reveal the problem, either because they don't have that specific Outlook iteration (there are far too many different versions without distinguishing names) or are running a different version or something.

The base64 thing turned out to be something else entirely.

We could potentially petition SendGrid to use HTTPS links by default, but I assume they have some legitimate reason to not use it, or they would have. Either way, I doubt this will affect very many people, and the images aren't important, so whatever.

2024-07-07 17:42 UTC, AdrianAndersen commented on src/config/environment.ts
> +  callback?: (value: string) => unknown,
We need it for the tests. We do not want to set like Twilio and SendGrid instances in the test environment, since the env is not available in the tests. Thus, the callbacks are for when we only want to run something when it is outside of tests

2024-07-07 17:49 UTC, AdrianAndersen commented on src/config/environment.ts
> +  callback?: (value: string) => unknown,
If we do it sequentially, twilio will display lots of warnings during the test since it has a regex on what it expects the env variable value to look like.

2024-07-07 17:55 UTC, LarsSelbekk commented on src/config/environment.ts
> +  callback?: (value: string) => unknown,
I don't think this is a sustainable way to do it - it's unintuitive that you should need to do it in a callback instead. Can we not rather mock in tests or use global dummy env variables in tests?

2024-07-07 17:55 UTC, LarsSelbekk requested changes
.

2024-07-07 18:11 UTC, AdrianAndersen commented on src/config/environment.ts
> +  callback?: (value: string) => unknown,
Found out that Mocha can actually load dotenv, so I did that instead. So now it is a bit smoother

2024-07-07 18:59 UTC, AdrianAndersen commented on src/config/environment.ts
> +  callback?: (value: string) => unknown,
Hmmmm, the actual env thing seemed cumbersome to setup, so I just opted to create some dummy placeholders to satisfy Twilio and Sendgrid

2024-07-08 22:38 UTC, LarsSelbekk approved these changes

2024-07-09 09:39 UTC, merged