feat(guardian-signature): implement public hook for guardian signatures
boklisten/bl-api pull request #538
Opened 2024-08-12 14:22 UTC by AdrianAndersen

2024-08-12 14:24 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Lage side og endepunkt for å registrere foreldresignaturer](https://trello.com/c/2baZ6OhK/1145-lage-side-og-endepunkt-for-%C3%A5-registrere-foreldresignaturer)

2024-08-13 14:55 UTC, LarsSelbekk requested changes

2024-08-13 15:39 UTC, AdrianAndersen commented on src/collections/signature/helpers/signature.helper.ts
> +export async function guardianSignatureRequired(
✅

2024-08-13 16:11 UTC, LarsSelbekk approved these changes

2024-08-13 21:44 UTC, merged